### ISSUE TITLE
"npm run build" fails (inferred type of 'default' cannot be named) 

### ISSUE THREAD

**Issue by HackyDev** [danielroe/nuxt-full-static#37]
### 🐛 The bug

Node 18.8.0
Npm 8.18.0
OS: Win11

I've just cloned the repo (v0.2.1), installed dependencies and issued `npm run build` command. Here's the output I got:

```
src/module.ts(5,1): error TS2742: The inferred type of 'default' cannot be named without a reference to '@nuxt/kit/node_modules/@nuxt/schema'. This is likely not portable. A type annotation is necessary.
src/module.ts(5,1): error TS2742: The inferred type of 'default' cannot be named without a reference to '@nuxt/kit/node_modules/@nuxt/schema'. This is likely not portable. A type annotation is necessary.

Error: Failed to compile. Check the logs above.
    at error (file:///C:/Users/iamma/Desktop/Dev/nuxt-full-static/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwPluginError (file:///C:/Users/iamma/Desktop/Dev/nuxt-full-static/node_modules/rollup/dist/es/shared/rollup.js:21781:12)
    at Object.error (file:///C:/Users/iamma/Desktop/Dev/nuxt-full-static/node_modules/rollup/dist/es/shared/rollup.js:22503:20)
    at Object.error (file:///C:/Users/iamma/Desktop/Dev/nuxt-full-static/node_modules/rollup/dist/es/shared/rollup.js:21958:42)
    at Object.transform (file:///C:/Users/iamma/Desktop/Dev/nuxt-full-static/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1590:26)
    at file:///C:/Users/iamma/Desktop/Dev/nuxt-full-static/node_modules/rollup/dist/es/shared/rollup.js:22710:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  id: 'C:\\Users\\iamma\\Desktop\\Dev\\nuxt-full-static\\src\\module.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'dts',
  watchFiles: [
    'C:\\Users\\iamma\\Desktop\\Dev\\nuxt-full-static\\src\\module.ts'
  ]
}
```

### 🛠️ To reproduce

https://stackblitz.com/github/danielroe/nuxt-full-static/tree/main/playground

### 🌈 Expected behaviour

Build process should succeed

**Comment by danielroe** [comment]
Try with these steps: https://github.com/danielroe/nuxt-full-static#-development

**Comment by danielroe** [comment]
Let me know if it doesn't work and I'll happily reopen. 🙏
